### ISSUE TITLE
Online Voter Registration

### ISSUE THREAD

**Issue by ocullenlopez** [Code4PuertoRico/paravotar#100]
__Please write your feedback as detailed as possible bellow.__
There is a high-profile push in the US to promote online voter registration and vote-by-mail (see https://twitter.com/WhenWeAllVote/status/1249687531593109505).

PR currently has no online voter registration platform and citizens likely don't trust the government can build one. There are several open source voter registration tools (see: http://web.mit.edu/vtp/ovr3.html) we could use if we wanted to explore building one.  

Vote by mail is a separate issue that I believe other groups can prioritize. From what I've seen, PR only supports absentee voting.

__Have you thought about any possible solutions or ways to approach this? If so please let us know!__

**Comment by eluciano11** [comment]
@ocullenlopez thanks for the feedback!

Yes, we have thought about online registrations and we don't think I will be able to be done for the upcoming elections. We think that doing something like that would require a lot of coordination with government agencies and we'd also need them to be onboard with the idea. As we've seen in this pandemic, time and technology are not allies of the PR government. That being said, I don't think it's an impossible task but in order to do this we'd need more time and the most importantly commitment from the government. 

Vote by mail would be a great alternative but I haven't seen any information about it on our research so I don't believe we have that in PR. 

Currently, PR has absentee and early voting but they are limited to some specific scenarios. For example, if you're working at a hospital and your work shift conflicts with the voting hours you can request an early vote.

We've added the different scenarios and requirements for absentee and early voting in paravotar.com.

**Comment by eluciano11** [comment]
Closing this for now.
